#!/usr/bin/env bash
# organize-for-drive.sh
# Creates an upload-ready folder structure matching the Google Drive organization.
# Run from the repo root: bash scripts/organize-for-drive.sh
# Then upload the generated 'drive-upload/' folder to Google Drive.

set -euo pipefail

GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
DEST="${PROJECT_ROOT}/drive-upload/AVops Agent Team"

cd "${PROJECT_ROOT}"

echo ""
echo -e "${BLUE}╔══════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║   Organizing files for Google Drive upload       ║${NC}"
echo -e "${BLUE}╚══════════════════════════════════════════════════╝${NC}"
echo ""

# Clean previous output
rm -rf "${DEST}"

# ── 01 — Documentation ──────────────────────────────────────────────────────
DIR="${DEST}/01 — Documentation"
mkdir -p "${DIR}"
cp CLAUDE.md "${DIR}/"
cp AGENT-TEAM-SETUP.md "${DIR}/"
cp docs/notebooklm-plan-export.md "${DIR}/"
cp docs/google-drive-inventory.md "${DIR}/"
echo -e "${GREEN}✓${NC} 01 — Documentation (4 files)"

# ── 02 — Agent Definitions ──────────────────────────────────────────────────
DIR="${DEST}/02 — Agent Definitions/Template Agents"
mkdir -p "${DIR}"
cp agents/*.md "${DIR}/"
echo -e "${GREEN}✓${NC} 02 — Agent Definitions / Template Agents (8 files)"

DIR="${DEST}/02 — Agent Definitions/Native Claude Code Agents"
mkdir -p "${DIR}"
cp .claude/agents/*.md "${DIR}/"
echo -e "${GREEN}✓${NC} 02 — Agent Definitions / Native Claude Code Agents (7 files)"

# ── 03 — Workflows ──────────────────────────────────────────────────────────
DIR="${DEST}/03 — Workflows"
mkdir -p "${DIR}"
cp workflows/*.md "${DIR}/"
echo -e "${GREEN}✓${NC} 03 — Workflows (7 files)"

# ── 04 — Scripts & Code ─────────────────────────────────────────────────────
DIR="${DEST}/04 — Scripts and Code"
mkdir -p "${DIR}"
cp scripts/init-agent-team.sh "${DIR}/"
cp scripts/organize-for-drive.sh "${DIR}/"
cp .claude/hooks/pre-tool-validate.sh "${DIR}/"
cp .claude/hooks/post-task-notify.sh "${DIR}/"
echo -e "${GREEN}✓${NC} 04 — Scripts and Code (4 files)"

# ── 05 — Configuration ──────────────────────────────────────────────────────
DIR="${DEST}/05 — Configuration"
mkdir -p "${DIR}"
cp .claude/settings.json "${DIR}/"
cp .gitignore "${DIR}/gitignore.txt"
cp .claude/workspace/AGENT_STATE.md "${DIR}/"
echo -e "${GREEN}✓${NC} 05 — Configuration (3 files)"

# ── 06 — Workspace Templates ────────────────────────────────────────────────
DIR="${DEST}/06 — Workspace Templates"
mkdir -p "${DIR}/plans" "${DIR}/docs-drafts" "${DIR}/research" "${DIR}/reviews"
echo "This directory holds implementation plans generated by the Planner agent." > "${DIR}/plans/README.txt"
echo "This directory holds draft documentation generated by the Documenter agent." > "${DIR}/docs-drafts/README.txt"
echo "This directory holds research outputs generated by the Researcher agent." > "${DIR}/research/README.txt"
echo "This directory holds review reports generated by the Reviewer agent." > "${DIR}/reviews/README.txt"
echo -e "${GREEN}✓${NC} 06 — Workspace Templates (4 placeholder READMEs)"

# ── Summary ──────────────────────────────────────────────────────────────────
echo ""
TOTAL=$(find "${DEST}" -type f | wc -l)
echo -e "${GREEN}Done!${NC} ${TOTAL} files organized into: drive-upload/AVops Agent Team/"
echo ""
echo "Upload the entire 'drive-upload/' folder to Google Drive."
echo ""
